# Training Workshop Part I
https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html

## Import Package paul

In [1]:
import pandas as pd
import numpy as np

In [2]:
a = 3
b = 6
print(a)
print(b)

3
6


In [4]:
# This is a Markdown
a = 5
a

5

In [46]:
print("this is a test")

this is a test


In [6]:
!python --version

Python 3.7.1


In [7]:
np.__version__

'1.15.4'

## Python Fundamentals

In this part, we will recap some fundamental operations in Python. 

In [8]:
# print('comment')
type('123')
#type(1 == 2)

str

In [9]:
a = 2 * 5 # assign values to variables
a # jupyter notebook won't print variable value in assignment

10

In [55]:
a * 199 # this is an expression, result is not stored

1990

In [10]:
# list
ages = [15,17,10,23,26,27,29,30]

In [11]:
new_ages = [e * 10 for e in ages] # for loop construction
new_ages

[150, 170, 100, 230, 260, 270, 290, 300]

In [12]:
# list can actually hold different types of values
combined = [15, 'str', 3.0, 'blah..']
combined

[15, 'str', 3.0, 'blah..']

In [13]:
# dict
menu = {
    "Big Mac": 3.99,
    "McSpicy": 5.45,
    "McWings": 4.25
}
menu

{'Big Mac': 3.99, 'McSpicy': 5.45, 'McWings': 4.25}

In [14]:
# iterate list values
for e in ages:
    print(e)

15
17
10
23
26
27
29
30


In [15]:
# iterate list with index and value
for i, e in enumerate(ages):
    print(i, e)

0 15
1 17
2 10
3 23
4 26
5 27
6 29
7 30


In [16]:
# key-value iteration over map
for k, v in menu.items():
    print(k, v)

Big Mac 3.99
McSpicy 5.45
McWings 4.25


In [17]:
for k in menu:
    print(k)

Big Mac
McSpicy
McWings


### function and lambda function

In [18]:
# function
def cube(x):
    return x * x * x
print(cube)
print(cube(3))

<function cube at 0x114fe3400>
27


In [19]:
# lambda function
g = lambda x: x * x * x
print(g)
print(g(3))
f=g
print(f)

<function <lambda> at 0x114fe3d08>
27
<function <lambda> at 0x114fe3d08>


In [20]:
# filter
nums = [5, 7, 22, 97, 54, 62, 77, 23, 73, 61] 
even_nums = list(filter(lambda x: (x%2 == 0) , nums))
print(filter(lambda x: (x%2 == 0) , nums))
print(even_nums)

[22, 54, 62]


In [21]:
# map
nums_2x = list(map(lambda x: x * 2, nums))
print(nums_2x)
#nums_3x = list(map(g, nums))
nums_3x = list(map(cube, nums))
print(nums_3x)

[10, 14, 44, 194, 108, 124, 154, 46, 146, 122]
[125, 343, 10648, 912673, 157464, 238328, 456533, 12167, 389017, 226981]


In [22]:
# reduce
from functools import reduce
nums_sum = reduce(lambda x, y: x + y, nums)
print(nums_sum)

481


## Numpy

In [22]:
import numpy as np

### Array Basics

In [23]:
x = np.array(nums)
print(x)
print(type(x))

[ 5  7 22 97 54 62 77 23 73 61]
<class 'numpy.ndarray'>


In [24]:
y = np.array([[2,5,6],[5,8,-1]])
print(y)
print(y.shape)
print(type(y.shape))

[[ 2  5  6]
 [ 5  8 -1]]
(2, 3)
<class 'tuple'>


In [28]:
# arrange [) (start from left boundary, with given steps)
m = np.arange(1,100,5)
print(m)
print(type(m))
print(m.shape)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
<class 'numpy.ndarray'>
(20,)


In [26]:
# linspace [] (evenly partitioned both boundaries are included)
m2 = np.linspace(1,10,7)
print(m2)
print(type(m2))
print(m2.dtype)

[ 1.   2.5  4.   5.5  7.   8.5 10. ]
<class 'numpy.ndarray'>
float64


In [31]:
# reshape
print(m)
print(m.reshape(10, 2))
print(m.reshape(4, 5))
#print(m.reshape(10,3))
print(m)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
[[ 1  6]
 [11 16]
 [21 26]
 [31 36]
 [41 46]
 [51 56]
 [61 66]
 [71 76]
 [81 86]
 [91 96]]
[[ 1  6 11 16 21]
 [26 31 36 41 46]
 [51 56 61 66 71]
 [76 81 86 91 96]]
[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [32]:
# resize
# resize changes the variable while reshape does not
print(x)
x.resize(2, 5)
print(x)

[ 5  7 22 97 54 62 77 23 73 61]
[[ 5  7 22 97 54]
 [62 77 23 73 61]]


In [33]:
print(np.ones((3,5)))
print(np.zeros(8))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
np.diag([2,5,6])

array([[2, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [36]:
t = np.ones((2,3), int)
print(t)
print(t + 10)

[[1 1 1]
 [1 1 1]]
[[11 11 11]
 [11 11 11]]


In [37]:
print(np.hstack([t, t+10]))
print((np.hstack([t, t+10])).shape)

[[ 1  1  1 11 11 11]
 [ 1  1  1 11 11 11]]
(2, 6)


In [38]:
print(np.vstack([t, t*2]))
# same as np.concatenate(t, t*2)

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


### Array Indexing and Slicing

In [39]:
x = np.array([[ 5,  7, 22, 97, 54],
    [62, 77, 23, 73, 61]])
print(x)
print('-----------------')
print(x[0,0])
print(x[1,2])
print(x[0:])
print(x[:,-3])
print(x[-1,::2])

[[ 5  7 22 97 54]
 [62 77 23 73 61]]
-----------------
5
23
[[ 5  7 22 97 54]
 [62 77 23 73 61]]
[22 23]
[62 23 61]


In [42]:
index_temp = x>10
print(index_temp.dtype)
print(x[x>10])

bool
[22 97 54 62 77 23 73 61]


In [46]:
# distinguish between slicing and slice assignment
x = np.array([[ 5,  7, 22, 97, 54],
    [62, 77, 23, 73, 61]])
print(x)
r = x[:,-3] # create a slice of x, assign to r
print(r)
#r[:] = 1 # as slice points to the original array, changing values affect original array

r = 1 # this is assignment, only changes value for r
print(r)
print(x)

[[ 5  7 22 97 54]
 [62 77 23 73 61]]
[22 23]
1
[[ 5  7 22 97 54]
 [62 77 23 73 61]]


In [47]:
r = 100
print(x)
x[:,-3] = 100
print(x)

[[ 5  7 22 97 54]
 [62 77 23 73 61]]
[[  5   7 100  97  54]
 [ 62  77 100  73  61]]


### Array Operation

In [40]:
a = [1.2,3.4,1.5]
b = [3,4,2]
from operator import mul
print(list(map(mul, a, b)))

[3.5999999999999996, 13.6, 3.0]


In [50]:
import numpy as np
a = [1.2,3.4,1.5]
b = [3,4,2]
print(a)
print(b)
print(np.array(a) * np.array(b))

[1.2, 3.4, 1.5]
[3, 4, 2]
[ 3.6 13.6  3. ]


In [51]:
np.array([2,5,8]).dot(np.array([0,1,2]))

21

In [52]:
x = np.array([[  5, 7, 1, 97, 54], [ 62, 77, 1, 100, 61]])
print(x)
x.T

[[  5   7   1  97  54]
 [ 62  77   1 100  61]]


array([[  5,  62],
       [  7,  77],
       [  1,   1],
       [ 97, 100],
       [ 54,  61]])

In [53]:
x.dtype

dtype('int64')

In [54]:
x.shape

(2, 5)

In [55]:
x.sum()

465

In [56]:
x.max()

100

In [103]:
x[1,3] = 100
print(x)
x.argmax()

[[  5   7 100  97  54]
 [ 62  77 100 100  61]]


2

In [57]:
np.sort(x)

array([[  1,   5,   7,  54,  97],
       [  1,  61,  62,  77, 100]])

In [58]:
np.ndarray.flatten(x)

array([  5,   7,   1,  97,  54,  62,  77,   1, 100,  61])

In [59]:
np.median(x)

57.5

In [60]:
print(np.mean(x))
print(np.sum(x)/np.size(x))

46.5
46.5


In [61]:
from scipy import stats

print(stats.mode(np.ndarray.flatten(x)))

##### exercise: how to implement mode with numpy functions #####

ModeResult(mode=array([1]), count=array([2]))


In [63]:
unique, counts = np.unique(x, return_counts=True)
print(unique)
print(counts)
print(counts.argmax())
print(x)

[  1   5   7  54  61  62  77  97 100]
[2 1 1 1 1 1 1 1 1]
0
[[  5   7   1  97  54]
 [ 62  77   1 100  61]]


In [64]:
np.split(x,2)

[array([[ 5,  7,  1, 97, 54]]), array([[ 62,  77,   1, 100,  61]])]

In [65]:
# arbitrary split
test_list = [2,3,6,7,1,23,22,3]
split_array = np.split(test_list,[2,6])
for e in split_array:
    print(e, len(e))

[2 3] 2
[ 6  7  1 23] 4
[22  3] 2


In [66]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)

######### what is the output ###########

[[0 0 1]
 [1 1 1]]


## Introduction to Dataframe

In [44]:
import pandas as pd
titanic = pd.read_csv("titanic.csv")

In [45]:
pd.options.display.max_rows = 30

In [46]:
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
..           ...       ...     ...   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
..                                                 ...     ...   ...    ...   
876                      Gustafsson, Mr. Alfred Ossian    male  20.0      0   
877                               Petroff, Mr. Nedelio    male  19.0      0   
878                                 Laleff, Mr. Kristo    male   NaN      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
883                      Banfield, Mr. Frederick James    male  28.0      0   
884                             Sutehall, Mr. Henry Jr    male  25.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  

In [8]:
# first n rows
titanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [197]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [11]:
titanic.index

RangeIndex(start=0, stop=891, step=1)

In [7]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [201]:
titanic.shape
# print(type(titanic.shape))

(891, 12)

In [8]:
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [12]:
min(titanic)
# returns the minimum column label

'Age'

In [13]:
titanic.min()

PassengerId                      1
Survived                         0
Pclass                           1
Name           Abbing, Mr. Anthony
Sex                         female
Age                           0.42
SibSp                            0
Parch                            0
Ticket                      110152
Fare                             0
dtype: object

## Built-in Functions and Methods

In [219]:
titanic.shape

(891, 12)

In [203]:
len(titanic)

891

In [218]:
titanic.size

10692

In [47]:
# round(dataframe, #digit)

round(titanic, 2)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
..           ...       ...     ...   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
..                                                 ...     ...   ...    ...   
876                      Gustafsson, Mr. Alfred Ossian    male  20.0      0   
877                               Petroff, Mr. Nedelio    male  19.0      0   
878                                 Laleff, Mr. Kristo    male   NaN      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
883                      Banfield, Mr. Frederick James    male  28.0      0   
884                             Sutehall, Mr. Henry Jr    male  25.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket   Fare Cabin Embarked  
0        0         A/5 21171   7.25   NaN        S  
1        0          PC 17599  71.28   C85        C  
2        0  STON/O2. 3101282   7.92   NaN        S  
3        0            113803  53.10  C123      

In [5]:
titanic.sort_values(by = 'Age', ascending=False)

PassengerId  Survived  Pclass  \
630          631         1       1   
851          852         0       3   
493          494         0       1   
96            97         0       1   
116          117         0       3   
672          673         0       2   
745          746         0       1   
33            34         0       2   
54            55         0       1   
280          281         0       3   
456          457         0       1   
438          439         0       1   
545          546         0       1   
275          276         1       1   
483          484         1       3   
570          571         1       2   
252          253         0       1   
829          830         1       1   
555          556         0       1   
625          626         0       1   
326          327         0       3   
170          171         0       1   
684          685         0       2   
694          695         0       1   
587          588         1       1   
366          367         1       1   
94            95         0       3   
232          233         0       2   
268          269         1       1   
11            12         1       1   
..           ...       ...     ...   
718          719         0       3   
727          728         1       3   
732          733         0       2   
738          739         0       3   
739          740         0       3   
740          741         1       1   
760          761         0       3   
766          767         0       1   
768          769         0       3   
773          774         0       3   
776          777         0       3   
778          779         0       3   
783          784         0       3   
790          791         0       3   
792          793         0       3   
793          794         0       1   
815          816         0       1   
825          826         0       3   
826          827         0       3   
828          829         1       3   
832          833         0       3   
837          838         0       3   
839          840         1       1   
846          847         0       3   
849          850         1       1   
859          860         0       3   
863          864         0       3   
868          869         0       3   
878          879         0       3   
888          889         0       3   

                                                 Name     Sex   Age  SibSp  \
630              Barkworth, Mr. Algernon Henry Wilson    male  80.0      0   
851                               Svensson, Mr. Johan    male  74.0      0   
493                           Artagaveytia, Mr. Ramon    male  71.0      0   
96                          Goldschmidt, Mr. George B    male  71.0      0   
116                              Connors, Mr. Patrick    male  70.5      0   
672                       Mitchell, Mr. Henry Michael    male  70.0      0   
745                      Crosby, Capt. Edward Gifford    male  70.0      1   
33                              Wheadon, Mr. Edward H    male  66.0      0   
54                     Ostby, Mr. Engelhart Cornelius    male  65.0      0   
280                                  Duane, Mr. Frank    male  65.0      0   
456                         Millet, Mr. Francis Davis    male  65.0      0   
438                                 Fortune, Mr. Mark    male  64.0      1   
545                      Nicholson, Mr. Arthur Ernest    male  64.0      0   
275                 Andrews, Miss. Kornelia Theodosia  female  63.0      1   
483                            Turkula, Mrs. (Hedwig)  female  63.0      0   
570                                Harris, Mr. George    male  62.0      0   
252                         Stead, Mr. William Thomas    male  62.0      0   
829         Stone, Mrs. George Nelson (Martha Evelyn)  female  62.0      0   
555                                Wright, Mr. George    male  62.0      0   
625                             Sutton, Mr. Frederick    male  61.0      0   
326       

## Indexing DataFrame


### select column

In [9]:
# select column
print(type(titanic['Age'])) # -> this returns a series
print(type(titanic[['Age']])) # -> this returns a dataframe

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


In [11]:
print(type(titanic[['Age', 'Sex']]))

<class 'pandas.core.frame.DataFrame'>


In [12]:
# select column with dot
print(titanic.Age)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
5       NaN
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
17      NaN
18     31.0
19      NaN
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
26      NaN
27     19.0
28      NaN
29      NaN
       ... 
861    21.0
862    48.0
863     NaN
864    24.0
865    42.0
866    27.0
867    31.0
868     NaN
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878     NaN
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64


In [14]:
# select column by dot equals to series as well
print(titanic.Age.equals(titanic['Age']))

True


### select rows

In [11]:
# 1st method: iloc
# position based index
titanic.iloc[2]

PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                                26
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object

In [12]:
# last row
titanic.iloc[-1]

PassengerId                    891
Survived                         0
Pclass                           3
Name           Dooley, Mr. Patrick
Sex                           male
Age                             32
SibSp                            0
Parch                            0
Ticket                      370376
Fare                          7.75
Cabin                          NaN
Embarked                         Q
Name: 890, dtype: object

In [13]:
# select row 2-4
titanic.iloc[2:5]

PassengerId  Survived  Pclass  \
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
2                        Heikkinen, Miss. Laina  female  26.0      0      0   
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   

             Ticket    Fare Cabin Embarked  
2  STON/O2. 3101282   7.925   NaN        S  
3            113803  53.100  C123        S  
4            373450   8.050   NaN        S

In [18]:
# select last 5 row
titanic.iloc[-5:]

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [22]:
# select a selection of rows
titanic.iloc[[2,5,141]] # -> params is a list

PassengerId  Survived  Pclass                      Name     Sex   Age  \
2              3         1       3    Heikkinen, Miss. Laina  female  26.0   
5              6         0       3          Moran, Mr. James    male   NaN   
141          142         1       3  Nysten, Miss. Anna Sofia  female  22.0   

     SibSp  Parch            Ticket    Fare Cabin Embarked  
2        0      0  STON/O2. 3101282  7.9250   NaN        S  
5        0      0            330877  8.4583   NaN        Q  
141      0      0            347081  7.7500   NaN        S

### combination of selection rows and columns

In [25]:
# iloc: first position is row, second position is column
titanic.iloc[0,3]

'Braund, Mr. Owen Harris'

In [26]:
# a range selection
titanic.iloc[[0,2,4], 3]

0     Braund, Mr. Owen Harris
2      Heikkinen, Miss. Laina
4    Allen, Mr. William Henry
Name: Name, dtype: object

In [29]:
titanic.iloc[[0,2,4], [3,5,8,9]]

Name   Age            Ticket   Fare
0   Braund, Mr. Owen Harris  22.0         A/5 21171  7.250
2    Heikkinen, Miss. Laina  26.0  STON/O2. 3101282  7.925
4  Allen, Mr. William Henry  35.0            373450  8.050

In [31]:
titanic.iloc[5,:]

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object

In [104]:
# second method: loc
# loc is label-based (the value of index)
titanic.loc[3]

NameError: name 'titanic' is not defined

In [49]:
newdf = titanic.set_index('Name')
newdf.loc['Rice, Master. Eugene']

PassengerId        17
Survived            0
Pclass              3
Sex              male
Age                 2
SibSp               4
Parch               1
Ticket         382652
Fare           29.125
Cabin             NaN
Embarked            Q
Name: Rice, Master. Eugene, dtype: object

In [52]:
newdf.loc['Rice, Master. Eugene', ['Age', 'Ticket']]

Age            2
Ticket    382652
Name: Rice, Master. Eugene, dtype: object

In [53]:
# slicing rows with loc
# label must be unique for slice
newdf.loc[:'Rice, Master. Eugene', ['Age', 'Ticket']]

Age            Ticket
Name                                                                      
Braund, Mr. Owen Harris                             22.0         A/5 21171
Cumings, Mrs. John Bradley (Florence Briggs Tha...  38.0          PC 17599
Heikkinen, Miss. Laina                              26.0  STON/O2. 3101282
Futrelle, Mrs. Jacques Heath (Lily May Peel)        35.0            113803
Allen, Mr. William Henry                            35.0            373450
Moran, Mr. James                                     NaN            330877
McCarthy, Mr. Timothy J                             54.0             17463
Palsson, Master. Gosta Leonard                       2.0            349909
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   27.0            347742
Nasser, Mrs. Nicholas (Adele Achem)                 14.0            237736
Sandstrom, Miss. Marguerite Rut                      4.0           PP 9549
Bonnell, Miss. Elizabeth                            58.0            113783
Saundercock, Mr. William Henry                      20.0         A/5. 2151
Andersson, Mr. Anders Johan                         39.0            347082
Vestrom, Miss. Hulda Amanda Adolfina                14.0            350406
Hewlett, Mrs. (Mary D Kingcome)                     55.0            248706
Rice, Master. Eugene                                 2.0            382652

In [54]:
newdf.loc[:'Rice, Master. Eugene', 'Age':'Ticket']

Age  SibSp  Parch  \
Name                                                                     
Braund, Mr. Owen Harris                             22.0      1      0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...  38.0      1      0   
Heikkinen, Miss. Laina                              26.0      0      0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)        35.0      1      0   
Allen, Mr. William Henry                            35.0      0      0   
Moran, Mr. James                                     NaN      0      0   
McCarthy, Mr. Timothy J                             54.0      0      0   
Palsson, Master. Gosta Leonard                       2.0      3      1   
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   27.0      0      2   
Nasser, Mrs. Nicholas (Adele Achem)                 14.0      1      0   
Sandstrom, Miss. Marguerite Rut                      4.0      1      1   
Bonnell, Miss. Elizabeth                            58.0      0      0   
Saundercock, Mr. William Henry                      20.0      0      0   
Andersson, Mr. Anders Johan                         39.0      1      5   
Vestrom, Miss. Hulda Amanda Adolfina                14.0      0      0   
Hewlett, Mrs. (Mary D Kingcome)                     55.0      0      0   
Rice, Master. Eugene                                 2.0      4      1   

                                                              Ticket  
Name                                                                  
Braund, Mr. Owen Harris                                    A/5 21171  
Cumings, Mrs. John Bradley (Florence Briggs Tha...          PC 17599  
Heikkinen, Miss. Laina                              STON/O2. 3101282  
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  113803  
Allen, Mr. William Henry                                      373450  
Moran, Mr. James                                              330877  
McCarthy, Mr. Timothy J                                        17463  
Palsson, Master. Gosta Leonard                                349909  
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)             347742  
Nasser, Mrs. Nicholas (Adele Achem)                           237736  
Sandstrom, Miss. Marguerite Rut                              PP 9549  
Bonnell, Miss. Elizabeth                                      113783  
Saundercock, Mr. William Henry                             A/5. 2151  
Andersson, Mr. Anders Johan                                   347082  
Vestrom, Miss. Hulda Amanda Adolfina                          350406  
Hewlett, Mrs. (Mary D Kingcome)                               248706  
Rice, Master. Eugene                                          382652

# Pandas Series

In [ ]:
age = titanic['Age']
age.dtype

### each row/column is a Series!!

In [ ]:
print(titanic.iloc[5])
print(type(titanic.iloc[5]))

In [17]:
print(age)
print(type(age))

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
5       NaN
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
17      NaN
18     31.0
19      NaN
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
26      NaN
27     19.0
28      NaN
29      NaN
       ... 
861    21.0
862    48.0
863     NaN
864    24.0
865    42.0
866    27.0
867    31.0
868     NaN
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878     NaN
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64
<class 'pandas.core.series.Series'>


In [59]:
age.describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

## analyzing series

In [60]:
age.sum()

21205.17

In [61]:
# sum cannot handle missing values
sum(age)

nan

In [63]:
age.size

891

In [64]:
len(age)

891

In [65]:
age.mean()

29.69911764705882

In [72]:
age.mean(skipna=False)

nan

In [74]:
# unique is only available for series
age.unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [75]:
age.nunique()

88

In [76]:
# nunique by default does not count nan/null
age.nunique(dropna=False)

89

In [80]:
age.value_counts()

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
28.00    25
21.00    24
25.00    23
36.00    22
29.00    20
32.00    18
27.00    18
35.00    18
26.00    18
16.00    17
31.00    17
20.00    15
33.00    15
23.00    15
34.00    15
39.00    14
17.00    13
42.00    13
40.00    13
45.00    12
38.00    11
50.00    10
2.00     10
4.00     10
47.00     9
         ..
71.00     2
59.00     2
63.00     2
0.83      2
30.50     2
70.00     2
57.00     2
0.75      2
13.00     2
10.00     2
64.00     2
40.50     2
32.50     2
45.50     2
20.50     1
24.50     1
0.67      1
14.50     1
0.92      1
74.00     1
34.50     1
80.00     1
12.00     1
36.50     1
53.00     1
55.50     1
70.50     1
66.00     1
23.50     1
0.42      1
Name: Age, Length: 88, dtype: int64

In [83]:
age.value_counts(normalize=True)

24.00    0.042017
22.00    0.037815
18.00    0.036415
19.00    0.035014
30.00    0.035014
28.00    0.035014
21.00    0.033613
25.00    0.032213
36.00    0.030812
29.00    0.028011
32.00    0.025210
27.00    0.025210
35.00    0.025210
26.00    0.025210
16.00    0.023810
31.00    0.023810
20.00    0.021008
33.00    0.021008
23.00    0.021008
34.00    0.021008
39.00    0.019608
17.00    0.018207
42.00    0.018207
40.00    0.018207
45.00    0.016807
38.00    0.015406
50.00    0.014006
2.00     0.014006
4.00     0.014006
47.00    0.012605
           ...   
71.00    0.002801
59.00    0.002801
63.00    0.002801
0.83     0.002801
30.50    0.002801
70.00    0.002801
57.00    0.002801
0.75     0.002801
13.00    0.002801
10.00    0.002801
64.00    0.002801
40.50    0.002801
32.50    0.002801
45.50    0.002801
20.50    0.001401
24.50    0.001401
0.67     0.001401
14.50    0.001401
0.92     0.001401
74.00    0.001401
34.50    0.001401
80.00    0.001401
12.00    0.001401
36.50    0.001401
53.00    0

In [85]:
age.value_counts(sort=True).head()

24.0    30
22.0    27
18.0    26
19.0    25
30.0    25
Name: Age, dtype: int64

In [89]:
age.value_counts(bins=10,sort=False)

(0.339, 8.378]       54
(8.378, 16.336]      46
(16.336, 24.294]    177
(24.294, 32.252]    169
(32.252, 40.21]     118
(40.21, 48.168]      70
(48.168, 56.126]     45
(56.126, 64.084]     24
(64.084, 72.042]      9
(72.042, 80.0]        2
Name: Age, dtype: int64

## create pandas series

### from dataframe

In [4]:
# a single row and a single column is a series
print(type(titanic.Age))
print(type(titanic.iloc[0]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


### create from list

In [5]:
pd.Series([2,5,6])

0    2
1    5
2    6
dtype: int64

In [6]:
# pass index
pd.Series([2,5,6], index=['two','five','six'])

two     2
five    5
six     6
dtype: int64

### create from dictionary

In [8]:
d = {"two":2, "five":5, "six":6}
pd.Series(d)

two     2
five    5
six     6
dtype: int64

### sort series

In [21]:
age = titanic.Age

# sort_values return a new series, won't affect original series
sorted_age = age.sort_values()
print(sorted_age.head())
print(age.head())

803    0.42
755    0.67
644    0.75
469    0.75
78     0.83
Name: Age, dtype: float64
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64


In [3]:
# use inplace to replace original series
tmp_num = pd.Series([2,3,4,1,100,15])
tmp_num.sort_values(inplace=True)
print(tmp_num)

3      1
0      2
1      3
2      4
5     15
4    100
dtype: int64


In [4]:
tmp_num.nlargest(3)

4    100
5     15
2      4
dtype: int64

In [23]:
tmp_num.idxmin()

3

### test: what if there are multiple max/min?

In [48]:
pd.Series([1,5,5,5,2,5,5,5]).idxmax()

1

In [25]:
sales = pd.Series([10,5,6,None,100], index=['Mon','Tue','Wed','Thu','Fri'])

In [26]:
print(sales)

Mon     10.0
Tue      5.0
Wed      6.0
Thu      NaN
Fri    100.0
dtype: float64


In [28]:
sales.iloc[2]

6.0

In [32]:
(sales*12.466).round(2)

Mon     124.66
Tue      62.33
Wed      74.80
Thu        NaN
Fri    1246.60
dtype: float64

## Pandas Index

In [33]:
sales.index

Index(['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], dtype='object')

In [34]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [35]:
titanic.index

RangeIndex(start=0, stop=891, step=1)

In [39]:
titanic.axes

[RangeIndex(start=0, stop=891, step=1),
 Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
        'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
       dtype='object')]

In [46]:
print(type(titanic.index))
print(type(titanic.columns))
# to change row index to base.Index, simple assign index as one of the column when loading csv

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.indexes.base.Index'>


### change index (row/column index of dataframe)

In [50]:
titanic.set_index('PassengerId', inplace=True)

In [51]:
titanic

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   
11                  1       3   
12                  1       1   
13                  0       3   
14                  0       3   
15                  0       3   
16                  1       2   
17                  0       3   
18                  1       2   
19                  0       3   
20                  1       3   
21                  0       2   
22                  1       2   
23                  1       3   
24                  1       1   
25                  0       3   
26                  1       3   
27                  0       3   
28                  0       1   
29                  1       3   
30                  0       3   
...               ...     ...   
862                 0       2   
863                 1       1   
864                 0       3   
865                 0       2   
866                 1       2   
867                 1       2   
868                 0       1   
869                 0       3   
870                 1       3   
871                 0       3   
872                 1       1   
873                 0       1   
874                 0       3   
875                 1       2   
876                 1       3   
877                 0       3   
878                 0       3   
879                 0       3   
880                 1       1   
881                 1       2   
882                 0       3   
883                 0       3   
884                 0       2   
885                 0       3   
886                 0       3   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   
11                             Sandstrom, Miss. Marguerite Rut  female   4.0   
12                                    Bonnell, Miss. Elizabeth  female  58.0   
13                              Saundercock, Mr. William Henry    male  20.0   
14                                 Andersson, Mr. Anders Johan    male  39.0   
15                        Vestrom, Miss. Hulda Amanda Adolfina  female  14.0   
16                            Hewlett, Mrs. (Mary D Kingcome)   female  55.0   
17                                        Rice, Master. Eugene    male   2.0   
18                                Williams, Mr. Charles Eugene    male   NaN   
19           Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0   
20                                     Masselmani, Mrs. Fatima  female   NaN   
21                                        Fynney, Mr. Joseph J    male  35.0   
22                                       Beesley, Mr. Lawrence    male  34.0   
23           

In [52]:
titanic.reset_index()

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [57]:
test_titanic = titanic.loc[:10,['Name', 'Sex']]

In [58]:
test_titanic

Name     Sex
PassengerId                                                           
1                                      Braund, Mr. Owen Harris    male
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female
3                                       Heikkinen, Miss. Laina  female
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
5                                     Allen, Mr. William Henry    male
6                                             Moran, Mr. James    male
7                                      McCarthy, Mr. Timothy J    male
8                               Palsson, Master. Gosta Leonard    male
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
10                         Nasser, Mrs. Nicholas (Adele Achem)  female

In [59]:
test_titanic.columns = ['New_name', "New_sex"]

In [61]:
test_titanic

New_name New_sex
PassengerId                                                           
1                                      Braund, Mr. Owen Harris    male
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female
3                                       Heikkinen, Miss. Laina  female
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
5                                     Allen, Mr. William Henry    male
6                                             Moran, Mr. James    male
7                                      McCarthy, Mr. Timothy J    male
8                               Palsson, Master. Gosta Leonard    male
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
10                         Nasser, Mrs. Nicholas (Adele Achem)  female